.PHONY: build clean

COMPILER_PREFIX?=$(TARGET_PREFIX)-

build:
	make CROSS_COMPILE=$(COMPILER_PREFIX)  ARCH=rv32im  PREFIX=build_rv32 \
	 IPFILTER=0 DHCP_SERVER=0 NAT=0 MCAST=1  \
	 PPP=0 IPV6=0 AODV=0 MDNS=1 TFTP=1
	
clean:
	make clean  PREFIX=build_rv32