.PHONY: build clean

COMPILER_PREFIX?=$(TARGET_PREFIX)-

build:
	make CROSS_COMPILE=$(COMPILER_PREFIX)  ARCH=rv32im  PREFIX=build_rv32 \
	 IPFILTER=0 DHCP_SERVER=0 NAT=0 MCAST=0 MDNS=0 \
	 PPP=0 IPV6=0 AODV=0 MDNS=0
	
clean:
	make clean  PREFIX=build_rv32